example_project/contests/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^list$', views.ContestsListView.as_view(), name='contests_list'),
]

example_project/example_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from sitewide.views import IndexView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^contests/', include('contests.urls', namespace='contests')),
    url(r'^slates/', include('slates.urls', namespace='slates')),
    url(r'^$', IndexView.as_view(), name='index'),
]

example_project/slates/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^list$', views.SlatesListView.as_view(), name='slates_list'),
]

example_project/contests/models.py
from django.db import models

# Create your models here.

example_project/slates/models.py
from django.db import models

# Create your models here.

example_project/contests/views.py
from django.views.generic.base import TemplateView


class ContestsListView(TemplateView):
    template_name = 'contests/contests_list.html'

example_project/sitewide/views.py
from django.views.generic.base import TemplateView


class IndexView(TemplateView):
    template_name = 'sitewide/index.html'

example_project/slates/views.py
from django.views.generic.base import TemplateView


class SlatesListView(TemplateView):
    template_name = 'slates/slates_list.html'

example_project/contests/templates/contests/contests_list.html
{% extends 'sitewide/base.html' %}
{% load static %}

{% block head_extra %}
<link rel="stylesheet" href="{% static 'contests/css/contests.css' %}" />
{% endblock %}

{% block main_content %}

<h1>Contests list</h1>

<div id="demo" class="mb-5"></div>

{% endblock %}

{% block extra_js %}
<script src="{% static 'contests/js/move.js' %}"></script>
{% endblock %}

example_project/example_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>Example project</title>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
	</head>
	<body>
		<nav class="navbar navbar-toggleable-sm navbar-inverse fixed-top bg-inverse">
			<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<a class="navbar-brand" href="/">Example project</a>

			<div class="collapse navbar-collapse" id="navbarsExampleDefault">
				<ul class="navbar-nav">
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="main_dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Stuff</a>
						<div class="dropdown-menu" aria-labelledby="main_dropdown">
							<a class="dropdown-item" href="{% url 'slates:slates_list' %}">Slates</a>
							<a class="dropdown-item" href="{% url 'contests:contests_list' %}">Contests</a>
						</div>
					</li>
				</ul>
			</div>
		</nav>

		<div class="main-content container-fluid">

			{% for message in messages %}
				<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					{{ message }}
				</div>
			{% endfor %}

			{% block body %}
			{% endblock %}

		</div>

		<!-- Run the JS -->
		<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

example_project/home/templates/home/index.html
{% extends 'base.html' %}

{% block body %}

<h1>Home</h1>

<ul>
	<li><a href="{% url 'slates:slates_list' %}">Slates</a></li>
	<li><a href="{% url 'contests:contests_list' %}">Contests</a></li>
</ul>

{% endblock %}

example_project/sitewide/templates/sitewide/base.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>Example project</title>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link rel="stylesheet" href="{% static 'sitewide/css/main.css' %}" />
		{% block head_extra %}
		{% endblock %}
	</head>
	<body>
		<nav class="navbar navbar-toggleable-sm navbar-inverse fixed-top bg-inverse">
			<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<a class="navbar-brand" href="/">Example project!</a>

			<div class="collapse navbar-collapse" id="navbarsExampleDefault">
				<ul class="navbar-nav">
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="main_dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Stuff</a>
						<div class="dropdown-menu" aria-labelledby="main_dropdown">
							<a class="dropdown-item" href="{% url 'slates:slates_list' %}">Slates</a>
							<a class="dropdown-item" href="{% url 'contests:contests_list' %}">Contests</a>
						</div>
					</li>
				</ul>
			</div>
		</nav>

		<div class="main-content container-fluid">

			{% for message in messages %}
				<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					{{ message }}
				</div>
			{% endfor %}

			{% block main_content %}
			{% endblock %}

		</div>

		<!-- Run the JS -->
		<script src="{% static 'sitewide/js/lib.js' %}"></script>

		{% block extra_js %}
		{% endblock %}

	</body>
</html>

example_project/sitewide/templates/sitewide/index.html
{% extends 'sitewide/base.html' %}
{% load static %}

{% block main_content %}

<h1>Home</h1>

<ul>
	<li><a href="{% url 'slates:slates_list' %}">Slates</a></li>
	<li><a href="{% url 'contests:contests_list' %}">Contests</a></li>
</ul>

<img src="{% static 'sitewide/img/sunpig_parent_child.jpg'%}" class="mv-3" />

{% endblock %}

example_project/slates/templates/slates/slates_list.html
{% extends 'sitewide/base.html' %}
{% load static %}

{% block head_extra %}
<link rel="stylesheet" href="{% static 'slates/css/slates.css' %}" />
{% endblock %}

{% block main_content %}

<h1>Slates list</h1>

<div id="demo" class="mb-5"></div>

{% endblock %}

{% block extra_js %}
<script src="{% static 'slates/js/rotate.js' %}"></script>
{% endblock %}